package com.email.system.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.email.system.dto.UserRequestDto;
import com.email.system.dto.UserResponseDto;
import com.email.system.entity.User;

@Mapper(componentModel  = "spring")
public interface UserMapper {
	
	@Mapping(target = "id", ignore = true)           // id is generated by DB
    @Mapping(target = "password", ignore = true)     // encode in service
    @Mapping(target = "role", ignore = true)         // default via entity
    @Mapping(target = "createdAt", ignore = true)
	User toEntity(UserRequestDto dto);
	
	UserResponseDto toUserResponseDto(User user);
}
